apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name:  lexeljacobflask
  namespace: lexeljacob 
  labels: 
    app:  lexeljacobflask
spec: 
  selector: 
    matchLabels: 
      app: lexeljacobflask
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate 
  template: 
    metadata: 
      labels: 
        app:  lexeljacobflask
    spec: 
      containers: 
      - name:  lexeljacobflask
        image:  lexeljacob/flask_app 
        resources: 
          requests: 
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m 
            memory: 100Mi 
        ports: 
        - containerPort:  5000 
          name:  lexeljacobflask
        imagePullPolicy: Always 
      restartPolicy: Always 
 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: lexeljacobflask
  namespace: lexeljacob 
spec: 
  selector: 
    app: lexeljacobflask
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: lexeljacobflask
    protocol: TCP 
    port: 80 
    targetPort: 5000 