apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name:  lexeljacobflaskcontainer
  namespace: lexeljacob 
  labels: 
    app:  lexeljacobflaskcontainer
spec: 
  selector: 
    matchLabels: 
      app: lexeljacobflaskcontainer
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate 
  template: 
    metadata: 
      labels: 
        app:  lexeljacobflaskcontainer
    spec: 
      containers: 
      - name:  lexeljacobflaskcontainer
        image:  lexeljacob/flask_app 
        resources: 
          requests: 
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m 
            memory: 100Mi 
        ports: 
        - containerPort:  5000 
          name:  lexeljacobflaskcontainer
        imagePullPolicy: Always 
      restartPolicy: Always 
 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: lexeljacobflaskcontainer
  namespace: lexeljacob 
spec: 
  selector: 
    app: lexeljacobflaskcontainer
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: lexeljacobflaskcontainer
    protocol: TCP 
    port: 80 
    targetPort: 5000 